name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # tag: v3.3.0
    - name: Setup Node.js
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # tag: v3.6.0
      with:
        node-version: 18.x
    - name: Create a Temporary package.json
      run: npm init --yes
    - name: Install @electron/lint-roller
      run: npm install --save-dev @electron/lint-roller
    - name: Lint
      run: |
        npx electron-markdownlint "**/*.md"
        npx electron-lint-markdown-links --root . --ignore-path .markdownlintignore "**/*.md"
